# Generated by Django 3.2.8 on 2021-11-25 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='post',
            name='pagenum',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
