# Generated by Django 3.2.8 on 2021-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211125_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default='2015'),
        ),
    ]
